name: 'Sprite Clean'
description: 'Clean up old sprites that were missed in previous CI runs'
author: 'cmbrose'

branding:
  icon: 'trash-2'
  color: 'red'

inputs:
  token:
    description: 'Sprites API token. If not provided, uses SPRITES_TOKEN environment variable.'
    required: false
  api-url:
    description: 'Sprites API URL. Defaults to https://api.sprites.dev'
    required: false
  mode:
    description: 'Cleanup mode: "global" for scheduled cleanup of old sprites, "current" for cleaning current workflow sprite. Default is inferred from context.'
    required: false
    default: ''
  max-age:
    description: 'Maximum age in hours for sprites to keep. Sprites older than this will be deleted. Only applies in global mode. Default: 24'
    required: false
    default: '24'
  dry-run:
    description: 'If true, only list sprites that would be deleted without actually deleting them'
    required: false
    default: 'false'
  sprite-prefix:
    description: 'Only clean sprites with names starting with this prefix. Only applies in global mode. Defaults to repo-specific prefix.'
    required: false
  sprite-name:
    description: 'Specific sprite name to delete. Only applies in current mode. If not provided, retrieved from action state.'
    required: false

outputs:
  sprites-cleaned:
    description: 'Number of sprites that were cleaned up'
  sprites-found:
    description: 'Total number of old sprites found'
  dry-run:
    description: 'Whether this was a dry run (true/false)'
  mode:
    description: 'The cleanup mode that was used (global/current)'

runs:
  using: 'node20'
  main: 'dist/index.js'