name: 'Sprite Run'
description: 'Execute a step with checkpoint management - skip if already completed, restore and run otherwise'
author: 'cmbrose'

branding:
  icon: 'play'
  color: 'green'

inputs:
  step-key:
    description: 'Unique identifier for this step within the job. Used to track checkpoint state.'
    required: true
  run:
    description: 'The bash command(s) to execute inside the sprite'
    required: true
  token:
    description: 'Sprites API token. If not provided, uses SPRITES_TOKEN environment variable.'
    required: false
  api-url:
    description: 'Sprites API URL. Defaults to https://api.sprites.dev'
    required: false
  sprite-id:
    description: 'Sprite ID from init action. If not provided, retrieved from action state.'
    required: false
  job-key:
    description: 'Job key from init action. If not provided, retrieved from action state.'
    required: false
  run-id:
    description: 'GitHub run ID. If not provided, retrieved from action state.'
    required: false
  last-checkpoint-id:
    description: 'Last checkpoint ID for restore. If not provided, retrieved from action state.'
    required: false
  workdir:
    description: 'Working directory for command execution inside the sprite'
    required: false

outputs:
  skipped:
    description: 'Whether the step was skipped due to existing checkpoint (true/false)'
  checkpoint-id:
    description: 'ID of the checkpoint created (or existing if skipped)'
  restored:
    description: 'Whether a restore from checkpoint occurred (true/false)'
  exit-code:
    description: 'Exit code of the executed command (0 if skipped)'

runs:
  using: 'node20'
  main: 'dist/index.js'
